name: bibleartwallpaperhd
description: Classical Bible Art.

publish_to: 'none'

version: 1.1.22+122

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.1.0
  provider: ^6.0.1
  sqflite: ^2.0.0+3
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  firebase_auth: ^4.2.2
  firebase_storage: ^11.0.10
#  platform_device_id: ^1.0.1
  admob_flutter: ^3.0.0
  app_tracking_transparency: ^2.0.2+1
  flutter_share: ^2.0.0
  flutter_downloader: ^1.5.2
  path_provider: ^2.0.7
  permission_handler: ^11.1.0
  image_gallery_saver: ^2.0.3
  dio: ^5.3.4
  rate_my_app: ^2.0.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.9
  group_radio_button: ^1.0.1
  purchases_flutter: ^6.4.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^16.2.0
  image_cropper: ^5.0.1
  merge_images: ^2.0.0-nullsafety
  cached_network_image: ^3.2.0
  intl: ^0.18.0
  url_launcher: ^6.0.5
  email_validator: ^2.0.1
  toast: ^0.3.0
  flutter_native_splash: ^2.2.6
  audioplayers: ^5.2.1
  file_picker: ^6.1.1
  flutter_wallpaper_manager: ^0.0.4
  progress_dialog_null_safe: ^1.0.7
  platform_device_id_v3: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon7.jpeg"

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/icon7.png
  color: "#ffffff"
  color_dark: "#ffffff"
  image_dark: assets/icon7.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/music/